'use strict';
(function() {

/**
 * ManualDialog - the user manual, inside the app.
 *
 * The manual is not a page beside the app but a data file within it
 * (js/data/manual-content.js, generated by tools/build-manual.js). That is
 * deliberate: `js/` is the app, so a manual carried there cannot go missing
 * while there is still an app to read it in, and there is no relative path to
 * a folder of images that could be wrong depending on how the app was opened.
 *
 * Three things worth knowing before changing this file.
 *
 * **Nothing is loaded at boot.** The manual is roughly half a megabyte with its
 * screenshots embedded, and most sessions never open it, so the script is
 * injected the first time somebody asks for it. A `<script>` tag is used rather
 * than `fetch` because this app runs from `file://`, where fetch is blocked and
 * script loading is not.
 *
 * **The styles are scoped, not isolated.** The app forbids shadow DOM, so the
 * manual's CSS is written scoped under `.manual` and the generator refuses to
 * build if a selector escapes that. The stylesheet is injected once and left in
 * place - it costs a few kilobytes and re-adding it on every open would be
 * churn for nothing.
 *
 * **The contents links are intercepted.** They are ordinary `#anchor` hrefs, so
 * left alone they would navigate the app's own document and, from `file://`,
 * reload it. The click handler scrolls the manual's scrolling element instead.
 */
class ManualDialogClass {
    constructor() {
        /** @type {?Promise<Object>} in-flight or completed load */
        this._loading = null;
        this._styleAdded = false;
    }

    /**
     * Load js/data/manual-content.js once, by injecting a script tag.
     *
     * The path is relative to the document, which is the entry file in both
     * layouts - `index.html` in the source tree, `PixULA.html` in the portable
     * build - and `js/` sits beside each.
     * @returns {Promise<Object>} the MANUAL_CONTENT payload
     * @private
     */
    _load() {
        if (window.MANUAL_CONTENT) return Promise.resolve(window.MANUAL_CONTENT);
        if (this._loading) return this._loading;

        this._loading = new Promise((resolve, reject) => {
            const script = document.createElement('script');
            script.src = 'js/data/manual-content.js';
            script.addEventListener('load', () => {
                if (window.MANUAL_CONTENT) resolve(window.MANUAL_CONTENT);
                else reject(new Error('manual-content.js loaded but set nothing'));
            });
            script.addEventListener('error', () =>
                reject(new Error('js/data/manual-content.js could not be loaded')));
            document.head.appendChild(script);
        });
        // A failed load must not poison every later attempt - the next Help >
        // Manual should try again rather than reporting the first failure for
        // the rest of the session.
        this._loading.catch(() => { this._loading = null; });
        return this._loading;
    }

    /** @private */
    _addStyle(css) {
        if (this._styleAdded) return;
        const style = document.createElement('style');
        style.id = 'manual-style';
        style.textContent = css;
        document.head.appendChild(style);
        this._styleAdded = true;
    }

    /**
     * Scroll to a heading inside the manual instead of navigating to it.
     * @param {HTMLElement} root
     * @private
     */
    _wireContents(root) {
        root.addEventListener('click', (e) => {
            const link = e.target.closest('a[href^="#"]');
            if (!link || !root.contains(link)) return;
            e.preventDefault();
            const target = root.querySelector('[id="' +
                CSS.escape(link.getAttribute('href').slice(1)) + '"]');
            if (target) target.scrollIntoView({ block: 'start' });
        });
    }

    /**
     * Open the manual.
     * @param {string} [anchor] - id of a heading to open at
     * @returns {Promise<void>}
     */
    async open(anchor) {
        let content;
        try {
            content = await this._load();
        } catch (err) {
            Logger.error('ManualDialog', err.message);
            Dialog.open({
                id: 'manual-dialog',
                titleI18n: 'menu.help.manual',
                title: 'Manual',
                content: (() => {
                    const p = document.createElement('p');
                    p.setAttribute('data-i18n', 'msg.manualMissing');
                    p.textContent = I18n.t('msg.manualMissing');
                    return p;
                })()
            });
            return;
        }

        this._addStyle(content.css);

        const root = document.createElement('div');
        root.className = 'manual';
        root.innerHTML = content.html;
        this._wireContents(root);

        Dialog.open({
            id: 'manual-dialog',
            titleI18n: 'menu.help.manual',
            title: 'Manual',
            className: 'manual-dialog',
            content: root
        });

        if (anchor) {
            const target = root.querySelector('[id="' + CSS.escape(anchor) + '"]');
            if (target) target.scrollIntoView({ block: 'start' });
        }
    }
}

window.ManualDialog = new ManualDialogClass();

})(); // End IIFE
